//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public int ID { get; set; }
        public int IDTypeCargo { get; set; }
        public string NameOfCargo { get; set; }
        public decimal Weight { get; set; }
        public string Description { get; set; }
        public int IDOrder { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual TypeOfCargo TypeOfCargo { get; set; }
    }
}
