//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightOrder
    {
        public int ID { get; set; }
        public int IDOrder { get; set; }
        public int IDFlight { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Order Order { get; set; }
    }
}
