//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.FlightOrder = new HashSet<FlightOrder>();
        }
    
        public int ID { get; set; }
        public int IDCityInp { get; set; }
        public int IDCityOut { get; set; }
        public System.DateTime DateOut { get; set; }
        public System.DateTime DateInp { get; set; }
        public int IDTransportVehicle { get; set; }
        public int IDStaff { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual TransportVehicle TransportVehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightOrder> FlightOrder { get; set; }
    }
}
